# Generated by Django 4.2.3 on 2023-08-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_addcyberuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcyberuser',
            old_name='computeruse',
            new_name='computeruse_id',
        ),
    ]
