# Generated by Django 4.2.3 on 2023-08-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_computeruse_addcyberuser_computeruse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcyberuser',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
