# Generated by Django 4.2.3 on 2023-08-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_addcyberuser_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcyberuser',
            name='entryid',
            field=models.IntegerField(default=0),
        ),
    ]
