# Generated by Django 4.2.3 on 2023-08-03 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_addcyberuser_entryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcyberuser',
            name='computeruse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.addcomputer'),
        ),
    ]
