# Generated by Django 4.2.3 on 2023-08-04 05:27

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_addcyberuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcyberuser',
            name='computeruse_id',
            field=models.IntegerField(verbose_name=authentication.models.AddComputer),
        ),
    ]
