# Generated by Django 4.2.3 on 2023-08-04 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_addcyberuser_computeruse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcyberuser',
            name='computeruse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.addcomputer'),
        ),
    ]
